config/routes.rb
Rails.application.routes.draw do

  resources :bookings do
    member do
        resources :charges
    end
  end



  root 'pages#home'
  get 'hostdashboard', to: 'pages#host_dashboard'
  get 'guestdashboard', to: 'pages#guest_dashboard'
  resources :rooms
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room

  scope :approved, -> { where(approved: true, paid: false) }
  scope :paid, -> {where(paid: true)}
  scope :pending, -> { where(approved: false) }
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :bookings

mount_uploaders :images, ImageUploader
serialize :images, JSON

end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :booking

  aftre_create :update_booking

  def update_booking
    booking.update_attributes(paied: true)
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action  :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:user_id, :room_id, :start_date, :end_date, :guest_number, :approved)
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  # def new
  #   @room = Room.find(params[:r])


end

def create
  @booking = Booking.find(params[:id])
  # Amount in cents
  @amount = (@booking.room.price * 100).to_i

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => "Booking id: #{@booking.id}",
    :currency    => 'aud'
  )

  @transaction = Transaction.create(amount: @amount, user_id: current_user.id, booking_id: @booking.id)

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
  # (r: @booking.room.id)
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def host_dashboard
  	# get approved and not approved bookings
  	# render template for that host
  	@rooms = current_user.rooms
  end

  def guest_dashboard
  	@bookings = current_user.bookings
  	@approved_bookings = @bookings.approved
  	@pending_bookings = @bookings.pending
    @paid_booking = @bookings.paid
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :description, :price, :capacity, :bathrooms, :pets, :smoking, :bath, :wifi, :share, :parties, :user_id, {images: []})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
	def yes_no(input)
		# if input
		# 	'yes'
		# else
		# 	'no'
		# end

		input ? 'yes' : 'no'
	end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(booking) do |f| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_select :end_date %>
  </div>

  <div class="field">
    <%= f.label :guest_number %>
    <%= f.number_field :guest_number %>
  </div>

  <div class="field">
  <% if params[:room_id].present? %>
    <%= f.hidden_field :room_id, value: params[:room_id] %>
  <% end %>
</div>

<p>If you own this booking would you like to approve it?</p>

  <div class="field">
  <%= f.label :approved %>
  <%= f.check_box :approved %>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>Guest number</th>
      <th>Room</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.start_date %></td>
        <td><%= booking.end_date %></td>
        <td><%= booking.guest_number %></td>
        <td><%= booking.room %></td>
        <td><%= booking.user %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @booking.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @booking.end_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @booking.user %>
</p>

<p>
  <strong>Guest number:</strong>
  <%= @booking.guest_number %>
</p>

<p>
  <strong>Room:</strong>
  <%= @booking.room %>
</p>




<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%= number_to_currency(@amount.to_d / 100) %></strong>!</h2>

<p> you booked <%= @booking.room.title %> </p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sleepovers</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:100" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abel|Oswald" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/nav' %>
  	<div class="container">
    <%= yield %>
  </body>
</html>

app/views/pages/guest_dashboard.html.erb
<h1>Guest Dashboard</h1>

<h3>Ready for Payment</h3>
<div class="panel panel-default">

    <div class="panel-heading">
		<tr>
			<th>Start</th>
			<th>End</th>
			<th>Cost</th>
			<th>Title</th>
			<th></th>
		</tr>
		</div>

		<table class="table">
		<% @approved_bookings.each do |booking| %>
			<tr>
				<td><%= booking.start_date %></td>
				<td><%= booking.end_date %></td>
				<td><%= number_to_currency(booking.room.price) %></td>
				<td><%= booking.room.title %></td>
				<td><%= render 'partials/stripe', booking: booking %></td>
			</tr>
		<% end %>
	</table>
</div>


<h3>Pending Approval</h3>

<h3>Already paid</h3>
<div class="panel panel-default">

    <div class="panel-heading">
		<tr>
			<th>Start</th>
			<th>End</th>
			<th>Cost</th>
			<th>Title</th>

		</tr>
		</div>

		<table class="table">
		<% @paid_booking.each do |booking| %>
			<tr>
				<td><%= booking.start_date %></td>
				<td><%= booking.end_date %></td>
				<td><%= number_to_currency(booking.room.price) %></td>
				<td><%= booking.room.title %></td>

			</tr>
		<% end %>
	</table>

app/views/pages/home.html.erb
<p class="header_home"><span class="name">Airbnb</span> Book unique homes and<br> experience a city like a local.</p>

<div class="search_bar">
<form class="navbar-form navbar-left" role="search">
  <div class="form-group">
    <input type="text" class="form-control" placeholder="Search">
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>
</div>

<div class="flex-container">
  <div class="flex-item1"></div>
  <div class="flex-item2"></div>
  <div class="flex-item3"></div>
  <div class="flex-item4"></div>
</div>
<br>
<div class"flex-container">
  <div class"flex_text1">For the happy-family</div>
  <div class"flex_text2">For the city-slicker</div>
  <div class"flex_text3">For me when I'm a super successful developer</div>
  <div class"flex_text4">For the nature lover</div>


</div>


<p></p>

app/views/pages/host_dashboard.html.erb
<h1>Host Dashboard</h1>

<!-- add user who booked a booking -->

<h3>My Bookings</h3>

<table class="table">
  <thead>
    <tr>
      <th>Start</th>
      <th>End</th>
      <th>Room</th>
      <th>Price</th>
      <th>Booking Time</th>
      <th>Guests #</th>
      <th>Approved?</th>
      <th>Update</th>
    </tr>
  </thead>
  <tbody>
		<% @rooms.each do |room| %>
			<% room.bookings.each do |booking| %>
				<tr>
	        <td><%= booking.start_date %></td>
	        <td><%= booking.end_date %></td>
	        <td><%= booking.room.title %></td>
	        <td><%= number_to_currency(booking.room.price) %></td>
	        <td><%= booking.created_at %></td>
	        <td><%= booking.guest_number %></td>
	        <td><%= yes_no(booking.approved) %></td>
	        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
	      </tr>
			<% end %>
		<% end %>
  </tbody>
</table>

<h3>My Rooms</h3>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Capacity</th>
      <th>Bathrooms</th>
      <th>Pets</th>
      <th>Smoking</th>
      <th>Wifi</th>
      <th>Bath</th>
      <th>Share</th>
      <th>Parties</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.title %></td>
        <td><%= room.price %></td>
        <td><%= room.capacity %></td>
        <td><%= room.bathrooms %></td>
        <td><%= room.pets %></td>
        <td><%= room.smoking %></td>
        <td><%= room.wifi %></td>
        <td><%= room.bath %></td>
        <td><%= room.share %></td>
        <td><%= room.parties %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
            <li>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            </li>
          <% else %>
            <li>
            <%= link_to('Login', new_user_session_path)  %>
            </li>
          <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/hostdashboard">Hosts</a></li>
        <li><a href="/guestdashboard">Guests</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/bookings/new">New Booking</a></li>
            <li><a href="/rooms/new">New Room</a></li>
            <li><a href="/rooms">availible rooms</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_stripe.html.erb
<%= form_tag charges_path(booking.id) do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Booking for: <%= booking.room.title %>"
          data-amount="<%= booking.room.price * 100 %>"
          data-locale="auto"></script>
<% end %>

app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :capacity %>
    <%= f.number_field :capacity %>
  </div>

  <div class="field">
    <%= f.label :bathrooms %>
    <%= f.number_field :bathrooms %>
  </div>

  <div class="field">
    <%= f.label :pets %>
    <%= f.check_box :pets %>
  </div>

  <div class="field">
    <%= f.label :smoking %>
    <%= f.check_box :smoking %>
  </div>

  <div class="field">
    <%= f.label :bath %>
    <%= f.check_box :bath %>
  </div>

  <div class="field">
    <%= f.label :wifi %>
    <%= f.check_box :wifi %>
  </div>

  <div class="field">
    <%= f.label :share %>
    <%= f.check_box :share %>
  </div>

  <div class="field">
    <%= f.label :parties %>
    <%= f.check_box :parties %>
  </div>

  <div class="field">
  <%= f.label :images %>
  <%= f.file_field :images, multiple: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>
<div class="panel panel-default">

    <div class="panel-heading">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Capacity</th>
      <th>Bathrooms</th>
      <th>User</th>
      <th>Pets</th>
      <th>Smoking</th>
      <th>Wifi</th>
      <th>Bath</th>
      <th>Share</th>
      <th>Parties</th>
      <th colspan="3"></th>
    </tr>
    </div>



     <table class="table">
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.title %></td>
        <td><%= room.description %></td>
        <td><%= room.price %></td>
        <td><%= room.capacity %></td>
        <td><%= room.bathrooms %></td>
        <td><%= room.user.email %></td>
        <td><%= room.pets %></td>
        <td><%= room.smoking %></td>
        <td><%= room.wifi %></td>
        <td><%= room.bath %></td>
        <td><%= room.share %></td>
        <td><%= room.parties %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

</table>
</div>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Book Now', new_booking_path(room_id: @room.id), class: 'btn btn-primary' %>

<p>
  <strong>Title:</strong>
  <%= @room.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@room.price) %> per night
</p>

<p>
  <strong>Capacity:</strong>
  <%= @room.capacity %>
</p>

<p>
  <strong>Bathrooms:</strong>
  <%= @room.bathrooms %>
</p>

<p>
  <strong>Pets:</strong>
  <%= yes_no(@room.pets) %>
</p>

<p>
  <strong>Smoking:</strong>
  <%= yes_no(@room.smoking) %>
</p>

<p>
  <strong>Bath:</strong>
  <%= yes_no(@room.bath) %>
</p>

<p>
  <strong>Wifi:</strong>
  <%= yes_no(@room.wifi) %>
</p>

<p>
  <strong>Share:</strong>
  <%= yes_no(@room.share) %>
</p>

<p>
  <strong>Parties:</strong>
  <%= yes_no(@room.parties) %>
</p>

<p>
  <strong>User:</strong>
  <%= @room.user.email %>
</p>

<% @room.images.each do |image| %>
  <img src="<%= image.url %>">
<% end %>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>